# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
   branches: [ "main" ]
  pull_request:

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    - name: Increment and commit version
      run: |
        cd TeleprompterRecorder
        bundle install
        sudo xcode-select -s '/Applications/Xcode_14.0.1.app'
        bundle exec fastlane deploygate_upload
      env:
        FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
        FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
        FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
        MATCH_KEYCHAIN_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}
        SLACK_URL: ${{ secrets.SLACK_URL }}
        DEPLOYGATE_API_KEY: ${{ secrets.DEPLOYGATE_API_KEY }}
        DEPLOYGATE_USER: ${{ secrets.DEPLOYGATE_USER }}
        APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
        APPLE_ID: ${{ secrets.APPLE_ID }}
        ITC_TEAM_ID: ${{ secrets.ITC_TEAM_ID }}
        TEAM_ID: ${{ secrets.TEAM_ID }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
        ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
        ASC_KEY_CONTENT: ${{ secrets.ASC_KEY_CONTENT }}
        PERSONAL_GITHUB_ACCESS_TOKEN: ${{ secrets.PERSONAL_GITHUB_ACCESS_TOKEN }}
        PERSONAL_GITHUB_USERNAME: ${{ secrets.PERSONAL_GITHUB_USERNAME }}
    - name: iOS Build Action
  # You may pin to the exact commit or the version.
  # uses: yukiarrr/ios-build-action@3d8ff63d40bce5dfd0ff8d1dda6ce543bf4c605a
      uses: yukiarrr/ios-build-action@v1.5.0
      with:
    # Base64 encoded p12 key
        p12-key-base64: ${{ secrets.P12_KEY_BASE64 }}
        # Base64 encoded certificate for the p12 key
        p12-cer-base64: ${{ secrets.P12_CER_BASE64 }}
        # Base64 encoded mobileprovision file
        mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
        # Project path
        project-path: ./TeleprompterRecorder/TeleprompterRecorder.xcodeproj
        # For example, iOS Distribution
        code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
        # Team id
        team-id: ${{ secrets.TEAM_ID }}
        # Choose app-store, ad-hoc, package, enterprise, development, or developer-id
        export-method: ad-hoc
        # Scheme
        scheme: TeleprompterRecorder
