# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
   branches: [ "main" ]
  pull_request:

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    - name: "Select the last available Xcode Beta"
      uses: BoundfoxStudios/action-xcode-select@v1
      with:
       version: "14.1"
    - name: necessary config
      run: |
        ls -a
        echo "${{ secrets.RELEASE_XCCONFIG }}" > ./TeleprompterRecorder/TeleprompterRecorder/Resource/Release.xcconfig.txt
        base64 -D -i ./TeleprompterRecorder/TeleprompterRecorder/Resource/Release.xcconfig.txt -o ./TeleprompterRecorder/TeleprompterRecorder/Resource/Release.xcconfig
        echo "${{ secrets.GOOGLESERVICE_INFO }}" > ./TeleprompterRecorder/TeleprompterRecorder/GoogleService-Info.plist.txt
        base64 -D -i ./TeleprompterRecorder/TeleprompterRecorder/GoogleService-Info.plist.txt -o ./TeleprompterRecorder/TeleprompterRecorder/GoogleService-Info.plist
    - name: Increment and commit version
      run: |
        cd TeleprompterRecorder
        ls -a ./TeleprompterRecorder/Resource
        bundle install
        bundle exec fastlane deploygate_upload
      env:
        FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
        FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
        FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
        MATCH_KEYCHAIN_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}
        SLACK_URL: ${{ secrets.SLACK_URL }}
        DEPLOYGATE_API_KEY: ${{ secrets.DEPLOYGATE_API_KEY }}
        DEPLOYGATE_USER: ${{ secrets.DEPLOYGATE_USER }}
        APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
        APPLE_ID: ${{ secrets.APPLE_ID }}
        ITC_TEAM_ID: ${{ secrets.ITC_TEAM_ID }}
        TEAM_ID: ${{ secrets.TEAM_ID }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
        ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
        ASC_KEY_CONTENT: ${{ secrets.ASC_KEY_CONTENT }}
        PERSONAL_GITHUB_ACCESS_TOKEN: ${{ secrets.PERSONAL_GITHUB_ACCESS_TOKEN }}
        PERSONAL_GITHUB_USERNAME: ${{ secrets.PERSONAL_GITHUB_USERNAME }}
    - name: Label Commenter
  # You may pin to the exact commit or the version.
  # uses: peaceiris/actions-label-commenter@f0dbbef043eb1b150b566db36b0bdc8b7f505579
      uses: peaceiris/actions-label-commenter@v1.10.0
      with:
        # Auth token used to manage issues or pull requests
        github_token: ${{ secrets.PERSONAL_GITHUB_ACCESS_TOKEN }}
    - name: Post comments
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_ACCESS_TOKEN }}
        URL: ${{ github.event.pull_request.html_url }}
      run:
        gh pr comment "${URL}" --body "DeployGate  https://deploygate.com/organizations/Enki/platforms/ios/apps/enki.TeleprompterRecorder"
