# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup SSH Keys and known_hosts for fastlane match
      # Copied from https://github.com/maddox/actions/blob/master/ssh/entrypoint.sh
      run: |
        SSH_PATH="$HOME/.ssh"

        mkdir -p "$SSH_PATH"
        touch "$SSH_PATH/known_hosts"

        echo "$PRIVATE_KEY" > "$SSH_PATH/id_rsa"

        chmod 700 "$SSH_PATH"
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        chmod 600 "$SSH_PATH/known_hosts"
        chmod 600 "$SSH_PATH/id_rsa"

        eval $(ssh-agent)
        ssh-add "$SSH_PATH/id_rsa"
      env:
        # 3: 秘匿情報の受け渡し
        PRIVATE_KEY: ${{ secrets.GITHUB_ACTIONS_SSH_PRIVATE_KEY }}

    - name: Run Fastlane - Deploy to AppStore Connect
      run: fastlane test
      env:
        FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
        FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
        FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
        MATCH_KEYCHAIN_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}
        SLACK_URL: ${{ secrets.SLACK_URL }}
        DEPLOYGATE_API_KEY: ${{ secrets.DEPLOYGATE_API_KEY }}
        DEPLOYGATE_USER: ${{ secrets.DEPLOYGATE_USER }}
        APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
        APPLE_ID: ${{ secrets.APPLE_ID }}
        ITC_TEAM_ID: ${{ secrets.ITC_TEAM_ID }}
        TEAM_ID: ${{ secrets.TEAM_ID }}
