# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Increment and commit version
      run: |
        xcodes select $XCODE_VERSION 
        bundle install
        bundle exec fastlane test
      env:
        XCODE_VERSION: '12.4'
    - name: Run Fastlane - Deploy to AppStore Connect
      run: bundle exec fastlane test
      env:
        FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
        FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
        FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
        MATCH_KEYCHAIN_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}
        SLACK_URL: ${{ secrets.SLACK_URL }}
        DEPLOYGATE_API_KEY: ${{ secrets.DEPLOYGATE_API_KEY }}
        DEPLOYGATE_USER: ${{ secrets.DEPLOYGATE_USER }}
        APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
        APPLE_ID: ${{ secrets.APPLE_ID }}
        ITC_TEAM_ID: ${{ secrets.ITC_TEAM_ID }}
        TEAM_ID: ${{ secrets.TEAM_ID }}
